package vip.e7du.subsystem.api.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseCity<M extends BaseBaseCity<M>> extends Model<M> implements IBean {

	public static final String table = "base_city";

	protected BaseBaseCity() {
		set(TABLE_KEY, BaseBaseCity.table);
	}

	public static final String ID = "id";

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public static final String NAME = "name";

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public static final String PROVINCE_ID = "province_id";

	public void setProvinceId(java.math.BigInteger provinceId) {
		set("province_id", provinceId);
	}

	public java.math.BigInteger getProvinceId() {
		return get("province_id");
	}

	public static final String LEVEL = "level";

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

	public static final String IS_OK = "is_ok";

	public void setIsOk(java.lang.Boolean isOk) {
		set("is_ok", isOk);
	}

	public java.lang.Boolean getIsOk() {
		return get("is_ok");
	}

	public static final String CREATE_DATE = "create_date";

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
