package vip.e7du.subsystem.api.model;

import vip.e7du.subsystem.api.base.model.BaseBaseCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseCity extends BaseBaseCity<BaseCity> {
	
}
