package vip.e7du.subsystem.api.model;

import vip.e7du.subsystem.api.base.model.BaseFireCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FireCity extends BaseFireCity<FireCity> {
	
}
