package vip.e7du.subsystem.api.model;

import vip.e7du.subsystem.api.base.model.BaseFireDistrict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FireDistrict extends BaseFireDistrict<FireDistrict> {
	
}
