package vip.e7du.subsystem.api.model;

import vip.e7du.subsystem.api.base.model.BaseFireProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FireProvince extends BaseFireProvince<FireProvince> {
	
}
